@Homesplash_HostAddress = http://localhost:5003

GET {{Homesplash_HostAddress}}/categories
Accept: application/json

###

POST {{Homesplash_HostAddress}}/linktiles
Content-Type: application/json

{
    "name": "GitHub",
    "link": "https://github.com",
    "categoryId": 1
}

###

GET {{Homesplash_HostAddress}}/linktiles
